apiVersion: apps/v1
kind: Deployment
metadata:
  name: ussd-app
  labels:
    app: ussdapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ussdapp
  template:
    metadata:
      labels:
        app: ussdapp
    spec:
      containers:
      - name: ussd
        image: tumbimsiska/ussdapp:v1
        ports:
        - containerPort: 8000
