apiVersion: v1
kind: Service
metadata:
  name: ussdapp-service
spec:
  type: NodePort
  selector:
    app: ussdapp
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
      nodePort: 31000
